apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proceedhub
resources:
  - namespace.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
configMapGenerator:
  - name: proceedhub-config
    literals:
      - PORT=8086
      - DB_URL=jdbc:postgresql://postgres:5432/proceedhub
      - JWT_EXPIRATION=3600000
      - CORS_ALLOWED_ORIGINS=http://localhost:8080
      - POSTGRES_DB=proceedhub
